//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingServerInitialSetup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string PasswordHash { get; set; }
        public string TOTPSecret { get; set; }
        public long RegistrationDateTime { get; set; }
        public string RegistrationDateTimeStr { get; set; }
        public bool Valid { get; set; }
        public bool Suspended { get; set; }
        public int DeviceCountLimit { get; set; }
        public long PaidTillDateTime { get; set; }
        public string PaidTillDateTimeStr { get; set; }
        public string DefaultContactPhone { get; set; }
        public string LicenseContent { get; set; }
    }
}
