//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingServerInitialSetup
{
    using System;
    using System.Collections.Generic;
    
    public partial class CryptoKeys
    {
        public long ID { get; set; }
        public byte[] PrivateKey { get; set; }
        public byte[] PublicKey { get; set; }
    }
}
