//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingServerInitialSetup
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public long ID { get; set; }
        public long DateTime { get; set; }
        public string DateTimeStr { get; set; }
        public string IPAddress { get; set; }
        public string EventText { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
    }
}
