//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingServerInitialSetup
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSettings
    {
        public long ID { get; set; }
        public string AdminEmail { get; set; }
        public string SiteName { get; set; }
        public string ServerEndPoint { get; set; }
        public string MailFromAddress { get; set; }
        public string EMailDisplayName { get; set; }
        public string RegDeviceMailSubject { get; set; }
        public string RegAccountMailSubject { get; set; }
        public bool MailUseSMTPAuth { get; set; }
        public string MailLogin { get; set; }
        public string MailPassword { get; set; }
        public string SMTPHost { get; set; }
        public int SMTPPort { get; set; }
        public bool SMTPUseSSL { get; set; }
        public string BingMapsAPIKey { get; set; }
        public string LastSavedDateTimeStr { get; set; }
    }
}
