//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AccountLog
{
    public long ID { get; set; }
    public string IPAddress { get; set; }
    public long DateTime { get; set; }
    public string DateTimeStr { get; set; }
    public string EventText { get; set; }
    public string Description { get; set; }
    public long AccountID { get; set; }
}

public partial class Accounts
{
    public long ID { get; set; }
    public string UserID { get; set; }
    public string PasswordHash { get; set; }
    public string TOTPSecret { get; set; }
    public long RegistrationDateTime { get; set; }
    public string RegistrationDateTimeStr { get; set; }
    public bool Valid { get; set; }
    public bool Suspended { get; set; }
    public int DeviceCountLimit { get; set; }
    public long PaidTillDateTime { get; set; }
    public string PaidTillDateTimeStr { get; set; }
    public string DefaultContactPhone { get; set; }
    public string LicenseContent { get; set; }
}

public partial class CryptoKeys
{
    public long ID { get; set; }
    public byte[] PrivateKey { get; set; }
    public byte[] PublicKey { get; set; }
}

public partial class SystemLog
{
    public long ID { get; set; }
    public long DateTime { get; set; }
    public string DateTimeStr { get; set; }
    public string IPAddress { get; set; }
    public string EventText { get; set; }
    public string Description { get; set; }
    public string UserID { get; set; }
}

public partial class WaterDeviceCommands
{
    public long ID { get; set; }
    public long WaterDeviceID { get; set; }
    public string Command { get; set; }
    public long FormedDatetime { get; set; }
    public string FormedDatetimeStr { get; set; }
    public long RequestedDatetime { get; set; }
    public string RequestedDatetimeStr { get; set; }
    public long AckDatetime { get; set; }
    public string AckDatetimeStr { get; set; }
    public string Result { get; set; }
}

public partial class WaterDeviceIncasso
{
    public long ID { get; set; }
    public long WaterDeviceID { get; set; }
    public long IncassoDatetime { get; set; }
    public string IncassoDatetimeStr { get; set; }
    public int IncassoCashboxCoins { get; set; }
    public decimal IncassoCashboxSum { get; set; }
    public int IncassoBABills { get; set; }
    public decimal IncassoBASum { get; set; }
    public long CommandID { get; set; }
}

public partial class WaterDevices
{
    public long ID { get; set; }
    public long AccountID { get; set; }
    public string HardwareID { get; set; }
    public long RegistrationDateTime { get; set; }
    public string RegistrationDateTimeStr { get; set; }
    public byte[] PublicKey { get; set; }
    public bool Valid { get; set; }
    public bool Suspended { get; set; }
    public bool PendingRegistration { get; set; }
    public string RegistrationRequest { get; set; }
    public long RegistrationRequestDateTime { get; set; }
    public string RegistrationRequestDateTimeStr { get; set; }
    public string LocationAddress { get; set; }
    public decimal LocationLatitude { get; set; }
    public decimal LocationLongtitude { get; set; }
    public string ProductName { get; set; }
    public string CustomerServiceContactPhone { get; set; }
    public int PRICE_PER_ITEM_MDE { get; set; }
    public string RegistrationResponse { get; set; }
    public string PendingRegistrationGUID { get; set; }
    public bool PendingRegConfirmed { get; set; }
    public string PendingRegConfirmationIP { get; set; }
    public long PendingRegConfirmationDateTime { get; set; }
    public string PendingRegConfirmationDateTimeStr { get; set; }
    public int TaxSystemType { get; set; }
    public long SettingsVersion { get; set; }
    public int WaterTankHeigthcm { get; set; }
    public bool UseKKT { get; set; }
    public byte[] WaterTempSensorAddress { get; set; }
}

public partial class WaterDeviceState : WaterDeviceTelemetry { }

public partial class WaterDeviceTelemetry
{
    public long ID { get; set; }
    public long DateTime { get; set; }
    public string DateTimeStr { get; set; }
    public long WaterDeviceID { get; set; }
    public int CC10RURCount { get; set; }
    public int CC5RURCount { get; set; }
    public int CC2RURCount { get; set; }
    public int CC1RURCount { get; set; }
    public decimal CCSum { get; set; }
    public int CBCount { get; set; }
    public decimal CBSum { get; set; }
    public decimal IncassoSum { get; set; }
    public decimal WaterTempCelsius { get; set; }
    public decimal InboxTempCelsius { get; set; }
    public decimal AmbientTempCelsius { get; set; }
    public decimal AmbientRelativeHumidity { get; set; }
    public int WaterLevelPercent { get; set; }
    public bool IsHeaterOn { get; set; }
    public bool IsExternalLightOn { get; set; }
    public bool IsFillPumpSocketActive { get; set; }
    public decimal TotalLitersDIspensed { get; set; }
    public decimal TotalHoursWorked { get; set; }
    public string KKTMfgNumber { get; set; }
    public bool KKTStageOpened { get; set; }
    public bool KKTStageOver24h { get; set; }
    public string KKTStageNumber { get; set; }
    public bool KKTReceiptOpened { get; set; }
    public int KKTCurrentMode { get; set; }
    public bool KKTPrinterConnected { get; set; }
    public bool KKTPrinterPaperEmpty { get; set; }
    public bool KKTPrinterNonRecoverableError { get; set; }
    public bool KKTPrinterCutterError { get; set; }
    public bool KKTPrinterOverHeated { get; set; }
    public bool KKTPrinterPaperJammed { get; set; }
    public bool KKTPrinterPaperEnding { get; set; }
    public int BABillsCount { get; set; }
    public decimal BASum { get; set; }
    public long LastStageClosedDateTime { get; set; }
    public string LastStageClosedDateTimeStr { get; set; }
    public int KKTReceiptNextNumber { get; set; }
    public string VMCMode { get; set; }
    public int MDBInitStep { get; set; }
    public string ProgramVersion { get; set; }
}

public partial class WaterSales
{
    public long ID { get; set; }
    public long WaterDeviceID { get; set; }
    public long StartDateTime { get; set; }
    public string StartDateTimeStr { get; set; }
    public decimal UserCash { get; set; }
    public decimal Quantity { get; set; }
    public int TaxSystemInUse { get; set; }
    public int PRICE_PER_ITEM_MDE { get; set; }
    public string ProductName { get; set; }
    public int ActualChangeDispensed { get; set; }
    public decimal ChangeActualDiff { get; set; }
    public long EndDateTime { get; set; }
    public string EndDateTimeString { get; set; }
    public long StageNumber { get; set; }
    public long ReceiptNumber { get; set; }
}

public partial class WebSettings
{
    public long ID { get; set; }
    public string AdminEmail { get; set; }
    public string SiteName { get; set; }
    public string ServerEndPoint { get; set; }
    public string MailFromAddress { get; set; }
    public string EMailDisplayName { get; set; }
    public string RegDeviceMailSubject { get; set; }
    public string RegAccountMailSubject { get; set; }
    public bool MailUseSMTPAuth { get; set; }
    public string MailLogin { get; set; }
    public string MailPassword { get; set; }
    public string SMTPHost { get; set; }
    public int SMTPPort { get; set; }
    public bool SMTPUseSSL { get; set; }
    public string BingMapsAPIKey { get; set; }
    public string LastSavedDateTimeStr { get; set; }
}
