

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class VendingModelContainer : DbContext
{
    public VendingModelContainer()
        : base("name=VendingModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Accounts> Accounts { get; set; }

    public virtual DbSet<WaterSales> WaterSales { get; set; }

    public virtual DbSet<WaterDeviceCommands> WaterDeviceCommands { get; set; }

    public virtual DbSet<WaterDeviceIncasso> WaterDeviceIncasso { get; set; }

    public virtual DbSet<WaterDevices> WaterDevices { get; set; }

    public virtual DbSet<WaterDeviceTelemetry> WaterDeviceTelemetry { get; set; }

    public virtual DbSet<CryptoKeys> CryptoKeys { get; set; }

    public virtual DbSet<WebSettings> WebSettings { get; set; }

    public virtual DbSet<AccountLog> AccountLog { get; set; }

    public virtual DbSet<SystemLog> SystemLog { get; set; }

    public virtual DbSet<WaterDeviceState> WaterDeviceState { get; set; }

}

